# -*- coding: utf-8 -*-
"""ContrastivePVP_ROC_CV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MtD2P1YiYxbk7PdqZk_ZU8GlNuvwV08I
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import (
    Dense, Conv1D, MaxPool1D, Flatten,
    SimpleRNN, GRU, LSTM, Bidirectional,
    Input
)
from tensorflow.keras.optimizers import Adam
from sklearn import metrics
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Input, Dense, SimpleRNN, LSTM, Bidirectional, Lambda
from tensorflow.keras.models import Model, Sequential
from sklearn.model_selection import KFold

train = pd.read_csv('/content/GTPC-train.csv')
test  = pd.read_csv('/content/GTPC-test.csv')

xtrain = train.drop(['Target'], axis=1).values
ytrain = train['Target'].values

xtest = test.drop(['Target'], axis=1).values
ytest = test['Target'].values

sample_size = xtrain.shape[0]
time_steps  = xtrain.shape[1]
input_dimension = 1

xtrain = xtrain.reshape(sample_size, time_steps, input_dimension)
xtest  = xtest.reshape(xtest.shape[0], time_steps, input_dimension)

n_timesteps = time_steps
n_features  = input_dimension

X = xtrain
Y = ytrain

cv_true_cnn, cv_pred_cnn = [], []
cv_true_rnn, cv_pred_rnn = [], []
cv_true_gru, cv_pred_gru = [], []
cv_true_lstm, cv_pred_lstm = [], []
cv_true_bilstm, cv_pred_bilstm = [], []
cv_true_rnn_bilstm, cv_pred_rnn_bilstm = [], []
cv_true_con, cv_pred_con = [], []

import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, SimpleRNN, LSTM, Bidirectional, Lambda
from tensorflow.keras.models import Model

def contrastive_encoder():
    inp = Input(shape=(n_timesteps, n_features))

    x = SimpleRNN(128, return_sequences=True, activation='tanh')(inp)
    x = Bidirectional(LSTM(64, return_sequences=False))(x)

    x = Dense(64)(x)

    # ✅ Keras-safe L2 normalization
    x = Lambda(lambda t: tf.math.l2_normalize(t, axis=1))(x)

    return Model(inp, x)
class SupConLoss(tf.keras.losses.Loss):
    def __init__(self, temperature=0.07):
        super().__init__()
        self.temperature = temperature

    def call(self, labels, features):
        labels = tf.reshape(labels, (-1, 1))
        mask = tf.cast(tf.equal(labels, tf.transpose(labels)), tf.float32)

        logits = tf.matmul(features, features, transpose_b=True) / self.temperature

        logits_mask = 1 - tf.eye(tf.shape(features)[0])
        mask = mask * logits_mask

        exp_logits = tf.exp(logits) * logits_mask
        log_prob = logits - tf.math.log(
            tf.reduce_sum(exp_logits, axis=1, keepdims=True) + 1e-12
        )

        loss = -tf.reduce_sum(mask * log_prob, axis=1) / tf.maximum(
            tf.reduce_sum(mask, axis=1), 1
        )

        return tf.reduce_mean(loss)

kf = KFold(n_splits=5, shuffle=True, random_state=42)

for fold, (train_index, val_index) in enumerate(kf.split(X), 1):
    print(f"========== Fold {fold} ==========")

    X_train, X_val = X[train_index], X[val_index]
    y_train, y_val = Y[train_index], Y[val_index]

    # ================= CNN =================
    cnn = Sequential()
    cnn.add(Conv1D(256, 2, activation='relu', input_shape=(X.shape[1], 1)))
    cnn.add(Conv1D(256, 2, activation='relu'))
    cnn.add(Conv1D(64, 2, activation='relu'))
    cnn.add(MaxPool1D(2))
    cnn.add(Flatten())
    cnn.add(Dense(64, activation='relu'))
    cnn.add(Dense(1, activation='sigmoid'))

    cnn.compile(optimizer=Adam(1e-4),
                loss='binary_crossentropy',
                metrics=['accuracy'])

    cnn.fit(X_train, y_train, epochs=75, batch_size=64, verbose=0)

    pred = cnn.predict(X_val).ravel()
    cv_true_cnn.extend(y_val)
    cv_pred_cnn.extend(pred)

    # ================= RNN =================
    rnn = Sequential()
    rnn.add(SimpleRNN(128, return_sequences=True, input_shape=(X.shape[1], 1)))
    rnn.add(SimpleRNN(64))
    rnn.add(Dense(64, activation='relu'))
    rnn.add(Dense(1, activation='sigmoid'))

    rnn.compile(optimizer=Adam(1e-4),
                loss='binary_crossentropy',
                metrics=['accuracy'])

    rnn.fit(X_train, y_train, epochs=75, batch_size=64, verbose=0)

    pred = rnn.predict(X_val).ravel()
    cv_true_rnn.extend(y_val)
    cv_pred_rnn.extend(pred)

    # ================= GRU =================
    gru = Sequential()
    gru.add(GRU(256, return_sequences=True, input_shape=(X.shape[1], 1)))
    gru.add(GRU(128, return_sequences=True))
    gru.add(GRU(64))
    gru.add(Dense(64, activation='relu'))
    gru.add(Dense(1, activation='sigmoid'))

    gru.compile(optimizer=Adam(1e-4),
                loss='binary_crossentropy',
                metrics=['accuracy'])

    gru.fit(X_train, y_train, epochs=75, batch_size=64, verbose=0)

    pred = gru.predict(X_val).ravel()
    cv_true_gru.extend(y_val)
    cv_pred_gru.extend(pred)

    # ================= LSTM =================
    lstm = Sequential()
    lstm.add(LSTM(128, return_sequences=True, input_shape=(X.shape[1], 1)))
    lstm.add(LSTM(64))
    lstm.add(Dense(64, activation='relu'))
    lstm.add(Dense(1, activation='sigmoid'))

    lstm.compile(optimizer=Adam(1e-4),
                 loss='binary_crossentropy',
                 metrics=['accuracy'])

    lstm.fit(X_train, y_train, epochs=75, batch_size=64, verbose=0)

    pred = lstm.predict(X_val).ravel()
    cv_true_lstm.extend(y_val)
    cv_pred_lstm.extend(pred)

    # ================= Bi-LSTM =================
    bi_lstm = Sequential()
    bi_lstm.add(Bidirectional(LSTM(256, return_sequences=True),
                              input_shape=(X.shape[1], 1)))
    bi_lstm.add(Bidirectional(LSTM(128, return_sequences=True)))
    bi_lstm.add(Bidirectional(LSTM(64)))
    bi_lstm.add(Dense(64, activation='relu'))
    bi_lstm.add(Dense(1, activation='sigmoid'))

    bi_lstm.compile(optimizer=Adam(1e-4),
                    loss='binary_crossentropy',
                    metrics=['accuracy'])

    bi_lstm.fit(X_train, y_train, epochs=75, batch_size=64, verbose=0)

    pred = bi_lstm.predict(X_val).ravel()
    cv_true_bilstm.extend(y_val)
    cv_pred_bilstm.extend(pred)

        # ================= RNN_Bi-LSTM =================
    rnn_bi_lstm = Sequential()
    rnn_bi_lstm.add(SimpleRNN(256, activation='tanh', return_sequences=True, input_shape=(X_train.shape[1], 1)))
    rnn_bi_lstm.add(SimpleRNN(128, activation='tanh', return_sequences=True))
    rnn_bi_lstm.add(SimpleRNN(64, activation='tanh', return_sequences=True))
    rnn_bi_lstm.add(Bidirectional(LSTM(64, activation='tanh', return_sequences=False)))
    rnn_bi_lstm.add(Dense(64, activation='relu'))
    rnn_bi_lstm.add(Dense(1, activation='sigmoid'))

    rnn_bi_lstm.compile(optimizer=Adam(1e-4),
                    loss='binary_crossentropy',
                    metrics=['accuracy'])

    rnn_bi_lstm.fit(X_train, y_train, epochs=75, batch_size=32, verbose=0)

    pred = rnn_bi_lstm.predict(X_val).ravel()
    cv_true_rnn_bilstm.extend(y_val)
    cv_pred_rnn_bilstm.extend(pred)

        # ================= ContrastivePVP =================
    encoder = contrastive_encoder()

    encoder.compile(
        optimizer=Adam(2e-3),
        loss=SupConLoss()
    )

    # Train encoder (contrastive)
    encoder.fit(
        X_train, y_train,
        epochs=33,
        batch_size=256,
        verbose=0
    )

    # Freeze encoder
    encoder.trainable = False

    contrastive_model = Sequential([
        encoder,
        Dense(64, activation='relu'),
        Dense(1, activation='sigmoid')
    ])

    contrastive_model.compile(
        optimizer=Adam(2e-3),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    # Train classifier head
    contrastive_model.fit(
        X_train, y_train,
        epochs=30,
        batch_size=64,
        verbose=0
    )

    # Validation prediction
    pred = contrastive_model.predict(X_val).ravel()
    cv_true_con.extend(y_val)
    cv_pred_con.extend(pred)

plt.rcParams["figure.figsize"] = [5, 3.5]
plt.rcParams.update({'font.family': 'serif'})

plt.xticks(weight='bold')
plt.yticks(weight='bold')

# Panel label
plt.text(-0.12, 1.05, "D",
         transform=plt.gca().transAxes,
         fontsize=16, fontweight='bold', va="top", ha="left")

# ---------- CNN ----------
fpr, tpr, _ = metrics.roc_curve(cv_true_cnn, cv_pred_cnn)
auc = metrics.roc_auc_score(cv_true_cnn, cv_pred_cnn)
plt.plot(fpr, tpr, color="#800000", label="CNN, AUC=" + str(round(auc, 3)))

# ---------- RNN ----------
fpr, tpr, _ = metrics.roc_curve(cv_true_rnn, cv_pred_rnn)
auc = metrics.roc_auc_score(cv_true_rnn, cv_pred_rnn)
plt.plot(fpr, tpr, color="#8A2BE2", label="RNN, AUC=" + str(round(auc, 3)))

# ---------- GRU ----------
fpr, tpr, _ = metrics.roc_curve(cv_true_gru, cv_pred_gru)
auc = metrics.roc_auc_score(cv_true_gru, cv_pred_gru)
plt.plot(fpr, tpr, color="#FFA500", label="GRU, AUC=" + str(round(auc, 3)))

# ---------- LSTM ----------
fpr, tpr, _ = metrics.roc_curve(cv_true_lstm, cv_pred_lstm)
auc = metrics.roc_auc_score(cv_true_lstm, cv_pred_lstm)
plt.plot(fpr, tpr, color="#7FBCFF", label="LSTM, AUC=" + str(round(auc, 3)))

# ---------- Bi-LSTM ----------
fpr, tpr, _ = metrics.roc_curve(cv_true_bilstm, cv_pred_bilstm)
auc = metrics.roc_auc_score(cv_true_bilstm, cv_pred_bilstm)
plt.plot(fpr, tpr, color="#008000", label="Bi-LSTM, AUC=" + str(round(auc, 3)))

# ---------- RNN_Bi-LSTM ----------
fpr, tpr, _ = metrics.roc_curve(cv_true_rnn_bilstm, cv_pred_rnn_bilstm)
auc = metrics.roc_auc_score(cv_true_rnn_bilstm, cv_pred_rnn_bilstm)
plt.plot(fpr, tpr, color="#ADADAD", label="RNN_Bi-LSTM, AUC=" + str(round(auc, 3)))

# ---------- ContrastivePVP ----------
fpr, tpr, _ = metrics.roc_curve(cv_true_con, cv_pred_con)
auc = metrics.roc_auc_score(cv_true_con, cv_pred_con)

plt.plot(fpr, tpr,color="#00008B",label="ContrastivePVP, AUC=" + str(round(auc, 3)))

plt.xlabel("False Positive Rate", fontweight='bold', fontsize=10)
plt.ylabel("True Positive Rate", fontweight='bold', fontsize=10)
plt.legend(loc='lower right', fontsize=12)

plt.tight_layout()
plt.savefig("ROC_5Fold_CV_D.png", bbox_inches="tight", dpi=800)
plt.savefig("ROC_5Fold_CV_D.pdf", bbox_inches="tight", dpi=800)
plt.show()