# -*- coding: utf-8 -*-
"""ContrastivePVP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rUtlmPMSPBTUu0qLzoYHtaD6oOTTC_GW
"""

import os
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import numpy as np
from sklearn.metrics import (
    accuracy_score, recall_score, precision_score,
    matthews_corrcoef, roc_auc_score,
    f1_score, cohen_kappa_score
)
import random

# Settings
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BATCH_SIZE = 128
CONTRASTIVE_EPOCHS = 21
CLASSIFIER_EPOCHS = 34
LR = 2e-3
FEATURE_COL_COUNT = 32
TRAIN_CSV = "/content/biobert-train.csv"
TEST_CSV = "/content/biobert-test.csv"

# Contrastive learning should use ONLY training data
CONTRASTIVE_CSV = TRAIN_CSV
SEED = 42

os.environ["PYTHONHASHSEED"] = str(SEED)
torch.manual_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)

# Dataset
class FeatureDataset(Dataset):
    def __init__(self, csv_file, feature_cols=None, target_col="Target",
                 timesteps=FEATURE_COL_COUNT, feature_dim=1):
        df = pd.read_csv(csv_file)
        if feature_cols is None:
            feature_cols = [c for c in df.columns if c != target_col]
        self.X = df[feature_cols].values.astype(np.float32)
        self.y = df[target_col].values.astype(np.int64)
        self.timesteps = timesteps
        self.feature_dim = feature_dim
        assert self.X.shape[1] == timesteps, f"Expected {timesteps}, got {self.X.shape[1]}"

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        x = self.X[idx].reshape(self.timesteps, self.feature_dim)
        return torch.from_numpy(x).float(), torch.tensor(self.y[idx], dtype=torch.long)


# Encoder
class RNNEncoder(nn.Module):
    def __init__(self, input_dim=1, rnn_hidden=128, bilstm_hidden=32, projection_dim=64):
        super().__init__()
        self.rnn1 = nn.RNN(input_dim, rnn_hidden, batch_first=True, nonlinearity="tanh")
        self.bilstm = nn.LSTM(rnn_hidden, bilstm_hidden, batch_first=True, bidirectional=True)
        self.fc = nn.Linear(bilstm_hidden * 2, projection_dim)

    def forward(self, x):
        out, _ = self.rnn1(x)
        _, (hn, _) = self.bilstm(out)
        hn_cat = torch.cat([hn[0], hn[1]], dim=1)
        proj = self.fc(hn_cat)
        return F.normalize(proj, dim=1)

# Supervised Contrastive Loss
class SupConLoss(nn.Module):
    def __init__(self, temperature=0.07):
        super().__init__()
        self.temperature = temperature

    def forward(self, features, labels):
        device = features.device
        labels = labels.view(-1, 1)
        mask = torch.eq(labels, labels.T).float().to(device)

        logits = torch.matmul(features, features.T) / self.temperature
        logits_mask = torch.ones_like(mask) - torch.eye(features.size(0), device=device)
        mask = mask * logits_mask

        exp_logits = torch.exp(logits) * logits_mask
        log_prob = logits - torch.log(exp_logits.sum(1, keepdim=True) + 1e-12)

        denom = torch.clamp(mask.sum(1), min=1.0)
        loss = -(mask * log_prob).sum(1) / denom
        return loss.mean()

# Classifier
class Classifier(nn.Module):
    def __init__(self, encoder, embedding_dim=64):
        super().__init__()
        self.encoder = encoder
        self.classifier = nn.Sequential(
            nn.Linear(embedding_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        with torch.no_grad():
            z = self.encoder(x)
        return self.classifier(z).squeeze(1)

# Training
def train_contrastive(encoder, loader):
    encoder.train()
    opt = torch.optim.Adam(encoder.parameters(), lr=LR)
    criterion = SupConLoss().to(DEVICE)

    for ep in range(1, CONTRASTIVE_EPOCHS + 1):
        total_loss = 0
        for x, y in loader:
            x, y = x.to(DEVICE), y.to(DEVICE)
            opt.zero_grad()
            loss = criterion(encoder(x), y)
            loss.backward()
            opt.step()
            total_loss += loss.item() * x.size(0)

        print(f"[Contrastive] Epoch {ep}/{CONTRASTIVE_EPOCHS} "
              f"Loss: {total_loss / len(loader.dataset):.6f}")
    return encoder

def train_classifier(classifier, loader):
    classifier.train()
    opt = torch.optim.Adam(classifier.parameters(), lr=LR)
    criterion = nn.BCELoss()

    for ep in range(1, CLASSIFIER_EPOCHS + 1):
        total_loss = 0
        for x, y in loader:
            x, y = x.to(DEVICE), y.float().to(DEVICE)
            opt.zero_grad()
            loss = criterion(classifier(x), y)
            loss.backward()
            opt.step()
            total_loss += loss.item() * x.size(0)

        print(f"[Classifier] Epoch {ep}/{CLASSIFIER_EPOCHS} "
              f"Loss: {total_loss / len(loader.dataset):.6f}")
    return classifier

# Evaluation (UPDATED)
def evaluate(classifier, loader):
    classifier.eval()
    preds, trues = [], []

    with torch.no_grad():
        for x, y in loader:
            x = x.to(DEVICE)
            out = classifier(x).cpu().numpy()
            preds.extend(out.tolist())
            trues.extend(y.numpy().tolist())

    preds_bin = [1 if p >= 0.5 else 0 for p in preds]

    acc = accuracy_score(trues, preds_bin)
    recall = recall_score(trues, preds_bin)
    precision = precision_score(trues, preds_bin)
    specificity = recall_score(trues, preds_bin, pos_label=0)
    f1 = f1_score(trues, preds_bin)
    kappa = cohen_kappa_score(trues, preds_bin)
    mcc = matthews_corrcoef(trues, preds_bin)
    auc = roc_auc_score(trues, preds)

    print(
        f"Accuracy: {acc:.4f} | Sensitivity: {recall:.4f} | "
        f"Specificity: {specificity:.4f}\n"
        f"Precision: {precision:.4f} | F1-score: {f1:.4f} | "
        f"Kappa: {kappa:.4f}\n"
        f"MCC: {mcc:.4f}"
    )

    return {
        "accuracy": acc,
        "recall": recall,
        "specificity": specificity,
        "precision": precision,
        "f1": f1,
        "kappa": kappa,
        "mcc": mcc
    }

# Helpers
def detect_feature_columns(csv_path, target_col="Target"):
    df = pd.read_csv(csv_path, nrows=1)
    return [c for c in df.columns if c != target_col]

# Main
def main():
    feature_cols = detect_feature_columns(CONTRASTIVE_CSV)
    assert len(feature_cols) == FEATURE_COL_COUNT

    contrastive_ds = FeatureDataset(CONTRASTIVE_CSV, feature_cols)
    train_ds = FeatureDataset(TRAIN_CSV, feature_cols)
    test_ds = FeatureDataset(TEST_CSV, feature_cols)

    contrastive_loader = DataLoader(contrastive_ds, BATCH_SIZE, shuffle=True, drop_last=True)
    train_loader = DataLoader(train_ds, BATCH_SIZE, shuffle=True)
    test_loader = DataLoader(test_ds, BATCH_SIZE, shuffle=False)

    encoder = RNNEncoder().to(DEVICE)
    encoder = train_contrastive(encoder, contrastive_loader)
    torch.save(encoder.state_dict(), "encoder_contrastive.pth")

    classifier = Classifier(encoder).to(DEVICE)
    classifier = train_classifier(classifier, train_loader)

    print("\nEvaluating on test set...")
    metrics = evaluate(classifier, test_loader)
    print("Done.")

if __name__ == "__main__":
    main()

from sklearn.model_selection import StratifiedKFold
from copy import deepcopy

# 5-Fold Cross Validation
def cross_validate_5fold(csv_path, feature_cols, n_splits=5):
    df = pd.read_csv(csv_path)

    X = df[feature_cols].values.astype(np.float32)
    y = df["Target"].values.astype(np.int64)

    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=SEED)

    fold_metrics = []

    for fold, (train_idx, val_idx) in enumerate(skf.split(X, y), 1):
        print(f"\n================ FOLD {fold} =================")

        # Create fold datasets
        train_df = df.iloc[train_idx]
        val_df   = df.iloc[val_idx]

        train_df.to_csv(f"cv_train_fold{fold}.csv", index=False)
        val_df.to_csv(f"cv_val_fold{fold}.csv", index=False)

        train_ds = FeatureDataset(f"cv_train_fold{fold}.csv", feature_cols)
        val_ds   = FeatureDataset(f"cv_val_fold{fold}.csv", feature_cols)

        train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
        val_loader   = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False)

        # Fresh encoder per fold
        encoder = RNNEncoder(
            input_dim=1,
            rnn_hidden=128,
            bilstm_hidden=32,
            projection_dim=64
        ).to(DEVICE)

        print("→ Contrastive training")
        encoder = train_contrastive(encoder, train_loader)

        # Classifier training
        classifier = Classifier(encoder, embedding_dim=64).to(DEVICE)
        print("→ Classifier training")
        classifier = train_classifier(classifier, train_loader)

        # Evaluation
        print("→ Validation evaluation")
        metrics = evaluate(classifier, val_loader)
        fold_metrics.append(metrics)

    return fold_metrics


# Run CV
feature_cols = detect_feature_columns(CONTRASTIVE_CSV, target_col="Target")

cv_results = cross_validate_5fold(
    csv_path=TRAIN_CSV,
    feature_cols=feature_cols,
    n_splits=5
)

# Aggregate Results
def summarize_cv(results):
    summary = {}
    for key in results[0].keys():
        values = [r[key] for r in results]
        summary[key] = {
            "mean": np.mean(values),
            "std":  np.std(values)
        }
    return summary

cv_summary = summarize_cv(cv_results)

print("\n=========== 5-FOLD CV RESULTS ===========")
for metric, stats in cv_summary.items():
    print(f"{metric.upper():12s}: {stats['mean']:.4f} ± {stats['std']:.4f}")

# 4-Panel t-SNE Visualization (Complete)
import torch
import numpy as np
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader
from sklearn.manifold import TSNE

# 1) Load trained encoder
encoder = RNNEncoder(input_dim=1, rnn_hidden=128, bilstm_hidden=32, projection_dim=64).to(DEVICE)
encoder.load_state_dict(torch.load("encoder_contrastive.pth", map_location=DEVICE))
encoder.eval()  # Set to evaluation mode

# 2) Prepare train/test datasets and loaders
train_ds = FeatureDataset(TRAIN_CSV)
test_ds = FeatureDataset(TEST_CSV)
train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False)

# 3) Function to extract raw and contrastive features
def extract_features(loader, sample_size):
    all_raw, all_con, all_labels = [], [], []
    with torch.no_grad():
        for x, y in loader:
            x_cpu = x.to(DEVICE).float()
            z = encoder(x_cpu).cpu().numpy()
            all_con.append(z)
            all_raw.append(x_cpu.cpu().numpy().reshape(x.shape[0], -1))
            all_labels.append(y.cpu().numpy())
            if sample_size and sum(len(b) for b in all_labels) >= sample_size:
                break
    X_raw = np.vstack(all_raw)[:sample_size]
    X_con = np.vstack(all_con)[:sample_size]
    y_all = np.concatenate(all_labels)[:sample_size]
    return X_raw, X_con, y_all

# Extract features
X_raw_train, X_con_train, y_train = extract_features(train_loader, sample_size=1000)
X_raw_test, X_con_test, y_test = extract_features(test_loader, sample_size=1000)

# 4) Compute t-SNE embeddings
def compute_tsne(X):
    n = len(X)
    perplexity = max(5, min(30, (n - 1) // 3))
    tsne = TSNE(n_components=2, perplexity=perplexity, learning_rate="auto",
                init="pca", random_state=42)
    return tsne.fit_transform(X)

tsne_raw_train = compute_tsne(X_raw_train)
tsne_con_train = compute_tsne(X_con_train)
tsne_raw_test = compute_tsne(X_raw_test)
tsne_con_test = compute_tsne(X_con_test)

# 5) Plot 4-panel t-SNE
plt.rcParams.update({
    "figure.dpi": 800,
    "font.family": "serif",   # ← generic serif (journal-safe)
})

fig, axes = plt.subplots(2, 2, figsize=(4, 4))
axes = axes.flatten()

data_list = [
    (tsne_raw_train, y_train, "Raw Features"),
    (tsne_con_train, y_train, "Contrastive Features"),
    (tsne_raw_test, y_test, "Raw Features"),
    (tsne_con_test, y_test, "Contrastive Features")
]

for i, (ax, (coords, labels, title)) in enumerate(zip(axes, data_list)):
    idx0 = (labels == 0)
    idx1 = (labels == 1)

    ax.scatter(coords[idx0, 0], coords[idx0, 1],
              s=6, alpha=0.8, label="Non-PVP",
              marker="o", color="#D62728")

    ax.scatter(coords[idx1, 0], coords[idx1, 1],
              s=6, alpha=0.8, label="PVP",
              marker="^", color="#00A5CF")


    ax.set_title(title, fontsize=9)
    ax.tick_params(axis='x', labelsize=7)
    ax.tick_params(axis='y', labelsize=7)

    # ---------- Axis label logic ----------
    row = i // 2
    col = i % 2

    # Y-axis label only for FIRST column
    if col == 0:
        ax.set_ylabel("t-SNE 2", fontsize=9)
    else:
        ax.set_ylabel("")

    # X-axis label only for LAST row
    if row == 1:
        ax.set_xlabel("t-SNE 1", fontsize=9)
    else:
        ax.set_xlabel("")
    # -------------------------------------

    # Show legend only for Train: Contrastive Features
    # if i == 1:
    #     ax.legend(loc='lower left', fontsize=6, frameon=True, framealpha=0.3)

fig.text(0.02, 0.995, "F", fontsize=12, fontweight="bold",
         ha="left", va="top")

plt.tight_layout()
plt.savefig("tsne_4panel_F_biobert.png", bbox_inches="tight", dpi=800)
plt.savefig("tsne_4panel_F_biobert.pdf", bbox_inches="tight", dpi=800)
plt.show()