# -*- coding: utf-8 -*-
"""ContrastivePVP_ROC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lr7L3yA_V_k534z8b8lvKDlHnK5D6huo
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import (
    Dense, Conv1D, MaxPool1D, Flatten,
    SimpleRNN, GRU, LSTM, Bidirectional,
    Input
)
from tensorflow.keras.optimizers import Adam
from sklearn import metrics
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Input, Dense, SimpleRNN, LSTM, Bidirectional, Lambda
from tensorflow.keras.models import Model, Sequential
from sklearn.model_selection import KFold

train = pd.read_csv('/content/GTPC-train.csv')
test  = pd.read_csv('/content/GTPC-test.csv')

xtrain = train.drop(['Target'], axis=1).values
ytrain = train['Target'].values

xtest = test.drop(['Target'], axis=1).values
ytest = test['Target'].values

sample_size = xtrain.shape[0]
time_steps  = xtrain.shape[1]
input_dimension = 1

xtrain = xtrain.reshape(sample_size, time_steps, input_dimension)
xtest  = xtest.reshape(xtest.shape[0], time_steps, input_dimension)

n_timesteps = time_steps
n_features  = input_dimension

cnn = Sequential()
cnn.add(Conv1D(256, 2, activation='relu', input_shape=(n_timesteps,n_features)))
cnn.add(Conv1D(256, 2, activation='relu'))
cnn.add(Conv1D(64, 2, activation='relu'))
cnn.add(MaxPool1D(2))
cnn.add(Flatten())
cnn.add(Dense(64, activation='relu'))
cnn.add(Dense(1, activation='sigmoid'))

cnn.compile(optimizer=Adam(1e-4), loss='binary_crossentropy', metrics=['accuracy'])


rnn = Sequential()
rnn.add(SimpleRNN(256, return_sequences=True, input_shape=(n_timesteps,n_features)))
rnn.add(SimpleRNN(32))
rnn.add(Dense(64, activation='relu'))
rnn.add(Dense(1, activation='sigmoid'))

rnn.compile(optimizer=Adam(1e-4), loss='binary_crossentropy', metrics=['accuracy'])


gru = Sequential()
gru.add(GRU(256, return_sequences=True, input_shape=(n_timesteps,n_features)))
gru.add(GRU(128, return_sequences=True))
gru.add(GRU(64))
gru.add(Dense(64, activation='relu'))
gru.add(Dense(1, activation='sigmoid'))

gru.compile(optimizer=Adam(1e-4), loss='binary_crossentropy', metrics=['accuracy'])


lstm = Sequential()
lstm.add(LSTM(128, return_sequences=True, input_shape=(n_timesteps,n_features)))
lstm.add(LSTM(64))
lstm.add(Dense(64, activation='relu'))
lstm.add(Dense(1, activation='sigmoid'))

lstm.compile(optimizer=Adam(1e-4), loss='binary_crossentropy', metrics=['accuracy'])


bi_lstm = Sequential()
bi_lstm.add(Bidirectional(LSTM(256, return_sequences=True), input_shape=(n_timesteps,n_features)))
bi_lstm.add(Bidirectional(LSTM(64)))
bi_lstm.add(Dense(64, activation='relu'))
bi_lstm.add(Dense(1, activation='sigmoid'))

bi_lstm.compile(optimizer=Adam(1e-4), loss='binary_crossentropy', metrics=['accuracy'])

rnn_bi_lstm = Sequential()
rnn_bi_lstm.add(SimpleRNN(128, activation='tanh', return_sequences=True, input_shape=(n_timesteps,n_features)))
rnn_bi_lstm.add(SimpleRNN(32, activation='tanh', return_sequences=True))
rnn_bi_lstm.add(Bidirectional(LSTM(32, activation='tanh', return_sequences=False)))
rnn_bi_lstm.add(Dense(64, activation='relu'))
rnn_bi_lstm.add(Dense(1, activation='sigmoid'))

rnn_bi_lstm.compile(optimizer=Adam(1e-4), loss='binary_crossentropy', metrics=['accuracy'])

def contrastive_encoder():
    inp = Input(shape=(n_timesteps, n_features))

    x = SimpleRNN(128, return_sequences=True, activation='tanh')(inp)
    x = Bidirectional(LSTM(64, return_sequences=False))(x)

    x = Dense(64)(x)

    # ✅ FIX: wrap L2 normalization inside Lambda
    x = Lambda(lambda t: tf.math.l2_normalize(t, axis=1))(x)

    return Model(inp, x)

#Supervised Contrastive loss
class SupConLoss(tf.keras.losses.Loss):
    def __init__(self, temperature=0.07):
        super().__init__()
        self.temperature = temperature

    def call(self, labels, features):
        labels = tf.reshape(labels, (-1,1))
        mask = tf.equal(labels, tf.transpose(labels))
        mask = tf.cast(mask, tf.float32)

        logits = tf.matmul(features, features, transpose_b=True) / self.temperature
        logits_mask = 1 - tf.eye(tf.shape(features)[0])
        mask = mask * logits_mask

        exp_logits = tf.exp(logits) * logits_mask
        log_prob = logits - tf.math.log(tf.reduce_sum(exp_logits, axis=1, keepdims=True) + 1e-12)

        loss = -tf.reduce_sum(mask * log_prob, axis=1) / tf.maximum(tf.reduce_sum(mask, axis=1), 1)
        return tf.reduce_mean(loss)
#Train Encoder
encoder = contrastive_encoder()

encoder.compile(
    optimizer=Adam(learning_rate=2e-3),
    loss=SupConLoss()
)

encoder.fit(
    xtrain,
    ytrain,
    epochs=33,
    batch_size=256,
    shuffle=True
)

#Contrastive Classifier
encoder.trainable = False

contrastive_model = Sequential([
    encoder,
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])

contrastive_model.compile(
    optimizer=Adam(learning_rate=2e-3),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

contrastive_model.fit(
    xtrain,
    ytrain,
    epochs=30,
    batch_size=64,
    shuffle=True
)

plt.rcParams["figure.figsize"] = [5, 3.5]
plt.rcParams.update({'font.family': 'serif'})

plt.xticks(weight='bold')
plt.yticks(weight='bold')

plt.text(-0.12, 1.05, "D",
         transform=plt.gca().transAxes,
         fontsize=16, fontweight="bold",
         va="top", ha="left")

cnn.fit(xtrain, ytrain, epochs=75, batch_size=64, verbose=0)
rnn.fit(xtrain, ytrain, epochs=75, batch_size=64, verbose=0)
gru.fit(xtrain, ytrain, epochs=75, batch_size=64, verbose=0)
lstm.fit(xtrain, ytrain, epochs=75, batch_size=64, verbose=0)
bi_lstm.fit(xtrain, ytrain, epochs=40, batch_size=64, verbose=0)
rnn_bi_lstm.fit(xtrain, ytrain, epochs=75, batch_size=32, verbose=0)


# ContrastivePVP already trained above
# (encoder + classifier trained separately)

pred = cnn.predict(xtest).ravel()
fpr, tpr, _ = metrics.roc_curve(ytest, pred)
auc = round(metrics.roc_auc_score(ytest, pred), 3)

plt.plot(fpr, tpr, color="#800000",
         label="CNN, AUC=" + str(auc))

pred = rnn.predict(xtest).ravel()
fpr, tpr, _ = metrics.roc_curve(ytest, pred)
auc = round(metrics.roc_auc_score(ytest, pred), 3)

plt.plot(fpr, tpr, color="#8A2BE2",
         label="RNN, AUC=" + str(auc))

pred = gru.predict(xtest).ravel()
fpr, tpr, _ = metrics.roc_curve(ytest, pred)
auc = round(metrics.roc_auc_score(ytest, pred), 3)

plt.plot(fpr, tpr, color="#FFA500",
         label="GRU, AUC=" + str(auc))

pred = lstm.predict(xtest).ravel()
fpr, tpr, _ = metrics.roc_curve(ytest, pred)
auc = round(metrics.roc_auc_score(ytest, pred), 3)

plt.plot(fpr, tpr, color="#7FBCFF",
         label="LSTM, AUC=" + str(auc))

pred = bi_lstm.predict(xtest).ravel()
fpr, tpr, _ = metrics.roc_curve(ytest, pred)
auc = round(metrics.roc_auc_score(ytest, pred), 3)

plt.plot(fpr, tpr, color="#008000",
         label="Bi-LSTM, AUC=" + str(auc))

pred = rnn_bi_lstm.predict(xtest).ravel()
fpr, tpr, _ = metrics.roc_curve(ytest, pred)
auc = round(metrics.roc_auc_score(ytest, pred), 3)

plt.plot(fpr, tpr, color="#ADADAD",
         label="RNN_Bi-LSTM, AUC=" + str(auc))

pred = contrastive_model.predict(xtest).ravel()
fpr, tpr, _ = metrics.roc_curve(ytest, pred)
auc = round(metrics.roc_auc_score(ytest, pred), 3)

plt.plot(fpr, tpr, color="#00008B",
         label="ContrastivePVP, AUC=" + str(auc))

plt.xlabel("False Positive Rate", fontweight='bold', fontsize=10)
plt.ylabel("True Positive Rate", fontweight='bold', fontsize=10)

plt.legend(loc='lower right', fontsize=12)
plt.tight_layout()

plt.savefig("ROC_Proposed_Test_D.png", bbox_inches="tight", dpi=800)
plt.savefig("ROC_Proposed_Test_D.pdf", bbox_inches="tight", dpi=800)
plt.show()